import { useState } from 'react';
const colors=['#c3f65b','#62d9cf','#a69aff','#ffbf76'];
export default function ChartVisual({title,rows,format=(n:number)=>n.toLocaleString('vi-VN'),variant='bars'}:{title:string;rows:{label:string;value:number}[];format?:(n:number)=>string;variant?:'bars'|'columns'|'donut'}) {
 const [hover,setHover]=useState<number|null>(null);
 const total=rows.reduce((sum,r)=>sum+r.value,0),max=Math.max(1,...rows.map(r=>r.value));
 const focused=hover===null?null:rows[hover];let offset=0;
 return <section className="report-chart"><header className="chart-heading"><div><span className="chart-eyebrow">THỐNG KÊ TRONG KỲ</span><h3>{title}</h3></div><div className="chart-total"><span>{focused?.label||'Tổng cộng'}</span><strong>{format(focused?.value??total)}</strong></div></header>
 {!rows.length||!total?<div className="chart-empty"><span aria-hidden="true">▂ ▅ ▃ ▇</span><p>Chưa có dữ liệu trong khoảng ngày đã chọn.</p></div>:variant==='donut'?<div className="chart-donut-layout"><div className="chart-ring"><svg viewBox="0 0 160 160" role="img" aria-label={rows.map(r=>`${r.label}: ${format(r.value)}`).join('; ')}><circle cx="80" cy="80" r="62" fill="none" stroke="#303a33" strokeWidth="19"/>{rows.map((r,i)=>{const part=r.value/total*100;const start=offset;offset+=part;return <circle key={r.label} cx="80" cy="80" r="62" fill="none" pathLength="100" stroke={colors[i%colors.length]} strokeWidth={hover===i?23:19} strokeDasharray={`${part} ${100-part}`} strokeDashoffset={-start} transform="rotate(-90 80 80)"><title>{r.label}: {format(r.value)}</title></circle>})}</svg><div><strong>100<span>%</span></strong><small>Cơ cấu trong kỳ</small></div></div><div className="chart-legend">{rows.map((r,i)=><button key={r.label} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)}><i style={{background:colors[i%colors.length]}}/><span>{r.label}<strong>{format(r.value)}</strong></span><b>{(r.value/total*100).toFixed(1)}%</b></button>)}</div></div>:variant==='columns'?<><div className="chart-column-scroll"><div className="chart-columns" style={{minWidth:Math.max(380,rows.length*44)}}>{rows.map((r,i)=><button className="chart-column" key={r.label+i} aria-label={`${r.label}: ${format(r.value)}`} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)}><span className="chart-column-track"><i style={{height:`${r.value/max*100}%`}}/></span><small>{r.label}</small><span className="chart-tooltip">{format(r.value)}</span></button>)}</div></div><div className="chart-scale"><span>Trục cột bắt đầu từ 0</span><span>Cao nhất: {format(max)}</span></div></>:<div className="chart-ranking" role="list" aria-label={title}>{rows.map((r,i)=><div className="chart-rank-row" role="listitem" key={r.label+i}><span className="chart-rank">{String(i+1).padStart(2,'0')}</span><div className="chart-bar-main"><div className="chart-bar-label"><span>{r.label}</span><strong>{format(r.value)}</strong></div><div className="report-chart-track"><div style={{width:`${r.value/max*100}%`,background:colors[i%colors.length]}}/></div></div></div>)}</div>}
 </section>;
}
