import test from 'node:test';
import assert from 'node:assert/strict';
process.env.GYM_TEST_MODE='1';
const {pool}=await import('../../backend/src/config/database.ts');
const {Database}=await import('../../backend/src/models/database.model.ts');
const {migrateWorkflows}=await import('../../backend/src/models/migration.model.ts');
const {act}=await import('../../backend/src/services/gym.service.ts');
const {quotePromotion}=await import('../../backend/src/services/promotion.service.ts');
const {todayVN,addDays}=await import('../../backend/src/utils/gym.ts');
test('MySQL holiday discount, assignment and rollback',async()=>{
 let c;
 try {
  await migrateWorkflows(); c=await pool.getConnection(); await c.beginTransaction();
  await c.query('SELECT id FROM mutation_lock WHERE id=1 FOR UPDATE');
  const db=new Database(c), run=(b,role='MANAGER')=>act(db,b,{id:'test',role});
  await c.query('UPDATE promotions SET active=0');
  const today=todayVN(), token=crypto.randomUUID();
  const base={action:'promotion.save',name:'Test holiday '+token,percent:20,start_date:today,end_date:today,active:1};
  await assert.rejects(()=>run({...base,percent:101}));
  await assert.rejects(()=>run({...base,end_date:addDays(today,-1)}));
  await assert.rejects(()=>run(base,'STAFF'),e=>e.status===403);
  const promo=await run(base);
  await run({...base,name:'Lower',percent:10});
  await run({...base,name:'Future',percent:90,start_date:addDays(today,1),end_date:addDays(today,2)});
  assert.equal((await quotePromotion(db,300000)).price,240000);
  const service=await run({action:'service.save',name:'Test service '+token,description:'',active:1});
  const other=await run({action:'service.save',name:'Other '+token,description:'',active:1});
  const coachBody={action:'trainer.save',name:'Test coach',phone:'09'+String(Math.floor(Math.random()*1e8)).padStart(8,'0'),email:'',experience:1,schedule:'Theo lịch',active:1,service_ids:[service.id,other.id]};
  const coach=await run(coachBody);
  assert.equal((await db.prepare('SELECT * FROM trainer_services WHERE trainer_id=?').bind(coach.id).all()).results.length,2);
  await run({action:'service.save',id:service.id,name:'Renamed '+token,description:'',active:1});
  assert(await db.prepare('SELECT * FROM trainer_services WHERE trainer_id=? AND service_id=?').bind(coach.id,service.id).first());
  await assert.rejects(()=>run({...coachBody,id:coach.id,service_ids:['missing']}));
  const member=await run({action:'member.save',name:'Test member',phone:'08'+String(Math.floor(Math.random()*1e8)).padStart(8,'0')});
  const plan=await run({action:'plan.save',name:'Test plan '+token,price:300000,days:30});
  const reg=await run({action:'registration.save',member_id:member.id,plan_id:plan.id,start_date:today});
  const stored=await db.prepare('SELECT * FROM registrations WHERE id=?').bind(reg.id).first();
  assert.equal(stored.price,240000);assert.equal(stored.discount_percent,20);assert.equal(stored.original_price,300000);
  await run({...base,id:promo.id,percent:50});
  assert.equal((await db.prepare('SELECT price FROM registrations WHERE id=?').bind(reg.id).first()).price,240000);
  await run({action:'payment.create',registration_id:reg.id,member_id:member.id,plan_id:plan.id,method:'Tiền mặt',request_id:crypto.randomUUID()});
  assert.equal((await db.prepare('SELECT amount FROM payments WHERE registration_id=?').bind(reg.id).first()).amount,240000);
  const room=await run({action:'room.save',name:'Test room',type:'Gym',capacity:10,active:1});
  await run({action:'schedule.save',member_id:member.id,trainer_id:coach.id,service_id:service.id,room_id:room.id,date:addDays(today,1),start_time:'09:00',end_time:'10:00'});
  await assert.rejects(()=>run({...coachBody,id:coach.id,service_ids:[other.id]}),e=>e.status===409);
  const member2=await run({action:'member.save',name:'Direct payment',phone:'07'+String(Math.floor(Math.random()*1e8)).padStart(8,'0')});
  const direct=await run({action:'payment.create',member_id:member2.id,plan_id:plan.id,method:'Tiền mặt',request_id:crypto.randomUUID()});
  assert.equal((await db.prepare('SELECT amount FROM payments WHERE id=?').bind(direct.id).first()).amount,150000);
  await run({...base,id:promo.id,percent:100});
  const member3=await run({action:'member.save',name:'Free promotion',phone:'06'+String(Math.floor(Math.random()*1e8)).padStart(8,'0')});
  const free=await run({action:'registration.save',member_id:member3.id,plan_id:plan.id,start_date:today});
  const freeRow=await db.prepare('SELECT * FROM registrations WHERE id=?').bind(free.id).first();
  assert.equal(freeRow.price,0);assert.equal(freeRow.status,'ACTIVE');
  await c.query('UPDATE promotions SET active=0');
  assert.equal((await quotePromotion(db,300000)).price,300000);
 } finally {if(c){await c.rollback();c.release();} await pool.end();}
});
